#!/usr/bin/env python3
"""Generate Figure 2 (Communication Timeline / Overlap) and Figure 3 (Bytes on Wire) for the paper."""
import os
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np

# Configure dark theme aesthetics matching the existing figures
plt.rcParams.update({
    'figure.facecolor': '#0d1117',
    'axes.facecolor': '#161b22',
    'axes.edgecolor': '#30363d',
    'axes.labelcolor': '#c9d1d9',
    'text.color': '#c9d1d9',
    'xtick.color': '#8b949e',
    'ytick.color': '#8b949e',
    'grid.color': '#21262d',
    'grid.alpha': 0.6,
    'font.family': 'sans-serif',
    'font.size': 11,
})

def plot_bytes_on_wire(out_dir):
    # Data for the configurations
    configs = [
        "Baseline",
        "LAER Only",
        "TWR Only",
        "EPEG + TWR",
        "Ours (Full Co-Design)"
    ]
    
    # Values in MB
    remote_bytes = np.array([9.50, 6.62, 9.50, 5.04, 3.51])
    local_bytes = np.array([0.66, 3.54, 0.66, 0.35, 1.88])
    
    fig, ax = plt.subplots(figsize=(10, 5))
    
    # Horizontal stacked bar chart
    bar_width = 0.5
    y_pos = np.arange(len(configs))
    
    # Plot Remote traffic (Inter-node RDMA / PCIe)
    b1 = ax.barh(y_pos, remote_bytes, bar_width, label="Remote Inter-Node (RDMA/PCIe)", color='#ff7b72', edgecolor='#30363d')
    # Plot Local traffic (Intra-node NVLink)
    b2 = ax.barh(y_pos, local_bytes, bar_width, left=remote_bytes, label="Local Intra-Node (NVLink)", color='#58a6ff', edgecolor='#30363d')
    
    # Add value labels
    for idx in range(len(configs)):
        total = remote_bytes[idx] + local_bytes[idx]
        ax.text(total + 0.15, idx, f"{total:.2f} MB", va='center', ha='left', fontweight='bold', color='#c9d1d9')
        
    ax.set_yticks(y_pos)
    ax.set_yticklabels(configs, fontweight='bold')
    ax.invert_yaxis()  # top-down order
    
    ax.set_xlabel("Total Transmitted Payload (MB)", fontsize=12, labelpad=10)
    ax.set_title("Payload on Wire: Local vs. Remote Network Footprint", fontsize=14, fontweight='bold', pad=20, color='#58a6ff')
    ax.grid(True, axis='x', alpha=0.3)
    ax.legend(loc="lower right", frameon=True, facecolor='#161b22', edgecolor='#30363d')
    ax.set_xlim(0, 11.5)
    
    plt.tight_layout()
    plot_path = os.path.join(out_dir, "bytes_on_wire.png")
    plt.savefig(plot_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Generated Bytes on Wire plot at: {plot_path}")

def plot_timeline_overlap(out_dir):
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 6.5), sharex=True)
    
    # 1. Baseline Timeline
    # GPUs send all at once, get congested, then stall, then complete.
    # GPU 0, 1, 2
    # Y-coordinates
    ax1.set_title("Collective Communication Timeline: Baseline vs. Topological Wavefront Routing", fontsize=14, fontweight='bold', pad=15, color='#58a6ff')
    
    # Baseline Bars
    # Ypos: 2 (GPU0), 1 (GPU1), 0 (GPU2)
    # SEND block, STALL block, COMPUTE block
    # format: (start, duration)
    ax1.barh(2, 4, left=0, height=0.4, color='#ff7b72', edgecolor='#30363d', label="Collective Dispatch")
    ax1.barh(2, 12, left=4, height=0.4, color='#7a2a29', hatch='//', edgecolor='#30363d', label="Congestion Stall (Timeout/PFC)")
    ax1.barh(2, 4, left=16, height=0.4, color='#f2d56a', edgecolor='#30363d', label="NPU Compute")
    
    ax1.barh(1, 4, left=0, height=0.4, color='#ff7b72', edgecolor='#30363d')
    ax1.barh(1, 12, left=4, height=0.4, color='#7a2a29', hatch='//', edgecolor='#30363d')
    ax1.barh(1, 4, left=16, height=0.4, color='#f2d56a', edgecolor='#30363d')
    
    ax1.barh(0, 4, left=0, height=0.4, color='#ff7b72', edgecolor='#30363d')
    ax1.barh(0, 12, left=4, height=0.4, color='#7a2a29', hatch='//', edgecolor='#30363d')
    ax1.barh(0, 4, left=16, height=0.4, color='#f2d56a', edgecolor='#30363d')
    
    ax1.set_yticks([0, 1, 2])
    ax1.set_yticklabels(["GPU 2", "GPU 1", "GPU 0"], fontweight='bold')
    ax1.set_ylabel("Baseline (All-to-All)", fontsize=11, fontweight='bold', labelpad=10)
    ax1.grid(True, alpha=0.2)
    ax1.legend(loc="upper right", frameon=True, facecolor='#161b22', edgecolor='#30363d', fontsize=9)
    
    # 2. TWR Coordinated Pipelining Timeline
    # Wavefront steps: Step 1, Step 2, Step 3, with concurrent compute
    # GPU 0: Comp 1 (0-3) -> Comm 1 & Comp 2 (3-7) -> Comm 2 & Comp 3 (7-11)
    # Let's plot these as blocks
    # GPU 0
    ax2.barh(2, 3, left=0, height=0.4, color='#f2d56a', edgecolor='#30363d') # Comp 1
    ax2.barh(2, 4, left=3, height=0.4, color='#10b981', edgecolor='#30363d', label="Coordinated Ring Dispatch (TWR Step 1)")
    ax2.barh(2, 4, left=7, height=0.4, color='#059669', edgecolor='#30363d', label="Coordinated Ring Dispatch (TWR Step 2)")
    # Overlapping compute (we draw a thinner compute bar on top of/overlapping the comm bars)
    ax2.barh(2.15, 3.5, left=3, height=0.1, color='#f2d56a', edgecolor='#30363d', label="Overlapped Local Compute")
    ax2.barh(2.15, 3.5, left=7, height=0.1, color='#f2d56a', edgecolor='#30363d')
    
    # GPU 1
    ax2.barh(1, 3, left=0, height=0.4, color='#f2d56a', edgecolor='#30363d') # Comp 1
    ax2.barh(1, 4, left=3, height=0.4, color='#059669', edgecolor='#30363d')
    ax2.barh(1, 4, left=7, height=0.4, color='#10b981', edgecolor='#30363d')
    ax2.barh(1.15, 3.5, left=3, height=0.1, color='#f2d56a', edgecolor='#30363d')
    ax2.barh(1.15, 3.5, left=7, height=0.1, color='#f2d56a', edgecolor='#30363d')
    
    # GPU 2
    ax2.barh(0, 3, left=0, height=0.4, color='#f2d56a', edgecolor='#30363d') # Comp 1
    ax2.barh(0, 4, left=3, height=0.4, color='#10b981', edgecolor='#30363d')
    ax2.barh(0, 4, left=7, height=0.4, color='#059669', edgecolor='#30363d')
    ax2.barh(0.15, 3.5, left=3, height=0.1, color='#f2d56a', edgecolor='#30363d')
    ax2.barh(0.15, 3.5, left=7, height=0.1, color='#f2d56a', edgecolor='#30363d')
    
    ax2.set_yticks([0, 1, 2])
    ax2.set_yticklabels(["GPU 2", "GPU 1", "GPU 0"], fontweight='bold')
    ax2.set_ylabel("TWR (Co-Design)", fontsize=11, fontweight='bold', labelpad=10)
    ax2.set_xlabel("Relative Time Steps (Normalized)", fontsize=12, labelpad=10)
    ax2.grid(True, alpha=0.2)
    ax2.legend(loc="upper right", frameon=True, facecolor='#161b22', edgecolor='#30363d', fontsize=9)
    ax2.set_xlim(0, 21)
    
    plt.tight_layout()
    plot_path = os.path.join(out_dir, "timeline_overlap.png")
    plt.savefig(plot_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f"Generated Timeline Overlap plot at: {plot_path}")

def main():
    out_dir = "outputs/phase5"
    os.makedirs(out_dir, exist_ok=True)
    
    plot_bytes_on_wire(out_dir)
    plot_timeline_overlap(out_dir)
    
    # Copy to the brain artifacts directory
    artifact_dir = "/home/palakm/.gemini/antigravity-ide/brain/ed3c2dc2-4e67-4959-b431-347772d4a219/sla_gating"
    os.makedirs(artifact_dir, exist_ok=True)
    import shutil
    shutil.copy(os.path.join(out_dir, "bytes_on_wire.png"), os.path.join(artifact_dir, "bytes_on_wire.png"))
    shutil.copy(os.path.join(out_dir, "timeline_overlap.png"), os.path.join(artifact_dir, "timeline_overlap.png"))
    print("Successfully copied plots to brain artifacts.")

if __name__ == "__main__":
    main()
